name: Update Metrics.
on:
  # Schedule updates (each day)
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: proTamizhan
          template: classic
          base: header, repositories
          config_timezone: Asia/Calcutta
